---
swagger: "2.0"
info:
  description: Detects face bounds, mouth and eyes from a picture URL
  title: Face Detection App
  version: 1.0.0
schemes:
- http
paths:
  /faces:
    get:
      description: Detects faces from a picture URL.
      parameters:
        - name: url
          in: query
          type: string
          format: uri
          required: true
      responses:
        200:
          description: list of detected faces
          schema:
            type: object
            properties:
              Faces:
                type: array
                items:
                  $ref: "#/definitions/Face"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  Face:
    type: object
    properties:
      bounds:
        $ref: "#/definitions/Rect"
      mouth:
        $ref: "#/definitions/Point"
      right_eye:
        $ref: "#/definitions/Point"
      left_eye:
        $ref: "#/definitions/Point"
  Rect:
    type: object
    properties:
      x:
        type: integer
        format: int64
      'y':
        type: integer
        format: int64
      height:
        type: integer
        format: int64
      width:
        type: integer
        format: int64
  Point:
    type: object
    properties:
      x:
        type: integer
        format: int64
      'y':
        type: integer
        format: int64
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
