// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/regeda/faced/models"
)

// GetFacesHandlerFunc turns a function with the right signature into a get faces handler
type GetFacesHandlerFunc func(GetFacesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFacesHandlerFunc) Handle(params GetFacesParams) middleware.Responder {
	return fn(params)
}

// GetFacesHandler interface for that can handle valid get faces params
type GetFacesHandler interface {
	Handle(GetFacesParams) middleware.Responder
}

// NewGetFaces creates a new http.Handler for the get faces operation
func NewGetFaces(ctx *middleware.Context, handler GetFacesHandler) *GetFaces {
	return &GetFaces{Context: ctx, Handler: handler}
}

/*GetFaces swagger:route GET /faces getFaces

Detects faces from a picture URL.

*/
type GetFaces struct {
	Context *middleware.Context
	Handler GetFacesHandler
}

func (o *GetFaces) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFacesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetFacesOKBody get faces o k body
//
// swagger:model GetFacesOKBody
type GetFacesOKBody struct {

	// faces
	Faces []*models.Face `json:"Faces"`
}

// Validate validates this get faces o k body
func (o *GetFacesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateFaces(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetFacesOKBody) validateFaces(formats strfmt.Registry) error {

	if swag.IsZero(o.Faces) { // not required
		return nil
	}

	for i := 0; i < len(o.Faces); i++ {
		if swag.IsZero(o.Faces[i]) { // not required
			continue
		}

		if o.Faces[i] != nil {
			if err := o.Faces[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getFacesOK" + "." + "Faces" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetFacesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFacesOKBody) UnmarshalBinary(b []byte) error {
	var res GetFacesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
