// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/regeda/faced/handlers (interfaces: Detector)

// Package handlers_test is a generated GoMock package.
package handlers_test

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/regeda/faced/models"
	io "io"
	reflect "reflect"
)

// MockDetector is a mock of Detector interface
type MockDetector struct {
	ctrl     *gomock.Controller
	recorder *MockDetectorMockRecorder
}

// MockDetectorMockRecorder is the mock recorder for MockDetector
type MockDetectorMockRecorder struct {
	mock *MockDetector
}

// NewMockDetector creates a new mock instance
func NewMockDetector(ctrl *gomock.Controller) *MockDetector {
	mock := &MockDetector{ctrl: ctrl}
	mock.recorder = &MockDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDetector) EXPECT() *MockDetectorMockRecorder {
	return m.recorder
}

// Detect mocks base method
func (m *MockDetector) Detect(arg0 io.Reader) ([]*models.Face, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", arg0)
	ret0, _ := ret[0].([]*models.Face)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detect indicates an expected call of Detect
func (mr *MockDetectorMockRecorder) Detect(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockDetector)(nil).Detect), arg0)
}
