// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Face Detection App
//
//  Detects face bounds, mouth and eyes from a picture URL
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
