// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Detects face bounds, mouth and eyes from a picture URL",
    "title": "Face Detection App",
    "version": "1.0.0"
  },
  "paths": {
    "/faces": {
      "get": {
        "description": "Detects faces from a picture URL.",
        "parameters": [
          {
            "type": "string",
            "format": "uri",
            "name": "url",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "list of detected faces",
            "schema": {
              "type": "object",
              "properties": {
                "Faces": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Face"
                  }
                }
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Face": {
      "type": "object",
      "properties": {
        "bounds": {
          "$ref": "#/definitions/Rect"
        },
        "left_eye": {
          "$ref": "#/definitions/Point"
        },
        "mouth": {
          "$ref": "#/definitions/Point"
        },
        "right_eye": {
          "$ref": "#/definitions/Point"
        }
      }
    },
    "Point": {
      "type": "object",
      "properties": {
        "x": {
          "type": "integer",
          "format": "int64"
        },
        "y": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Rect": {
      "type": "object",
      "properties": {
        "height": {
          "type": "integer",
          "format": "int64"
        },
        "width": {
          "type": "integer",
          "format": "int64"
        },
        "x": {
          "type": "integer",
          "format": "int64"
        },
        "y": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Detects face bounds, mouth and eyes from a picture URL",
    "title": "Face Detection App",
    "version": "1.0.0"
  },
  "paths": {
    "/faces": {
      "get": {
        "description": "Detects faces from a picture URL.",
        "parameters": [
          {
            "type": "string",
            "format": "uri",
            "name": "url",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "list of detected faces",
            "schema": {
              "type": "object",
              "properties": {
                "Faces": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Face"
                  }
                }
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Face": {
      "type": "object",
      "properties": {
        "bounds": {
          "$ref": "#/definitions/Rect"
        },
        "left_eye": {
          "$ref": "#/definitions/Point"
        },
        "mouth": {
          "$ref": "#/definitions/Point"
        },
        "right_eye": {
          "$ref": "#/definitions/Point"
        }
      }
    },
    "Point": {
      "type": "object",
      "properties": {
        "x": {
          "type": "integer",
          "format": "int64"
        },
        "y": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Rect": {
      "type": "object",
      "properties": {
        "height": {
          "type": "integer",
          "format": "int64"
        },
        "width": {
          "type": "integer",
          "format": "int64"
        },
        "x": {
          "type": "integer",
          "format": "int64"
        },
        "y": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
